# Generated by Django 5.1.3 on 2025-06-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0003_alter_geolocation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ['-timestamp']},
        ),
    ]
